project:
  type: website
  output-dir: docs

website:
  title: "Wesley Covey"
  favicon: images/favicon2.ico
  navbar:
    logo: images/favicon2.ico
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Portfolio

format:
  html:
    theme:
      dark: darkly
      light: flatly
      #- cosmo
      #- brand
    css: styles.css
    toc: true
    toc-location: left
