project:
  type: website
  output-dir: docs

website:
  title: "Wesley Covey"
  favicon: images/favicon3.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house
      - href: resume.qmd
        text: Resume
        icon: file-text
      - href: projects.qmd
        text: Portfolio
        icon: folder2-open
      - href: bonus.qmd
        text: Bonus
        icon: gem

format:
  html:
    theme:
      dark: darkly
      light: flatly
      #- cosmo
      #- brand
    css: styles.css
    toc: true
    toc-location: left
