project:
  type: website
  output-dir: docs

website:
  title: "Wesley Covey"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Portfolio

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



